// @generated by scripts/gen_sobol_tables.py - do not edit by hand.

mod jaeckel_data_0;
mod jaeckel_offsets;
mod joe_kuo_d5_data_0;
mod joe_kuo_d5_offsets;
mod joe_kuo_d6_data_0;
mod joe_kuo_d6_data_1;
mod joe_kuo_d6_offsets;
mod joe_kuo_d7_data_0;
mod joe_kuo_d7_offsets;
mod kuo2_data_0;
mod kuo2_offsets;
mod kuo3_data_0;
mod kuo3_offsets;
mod kuo_data_0;
mod kuo_offsets;
mod lemieux_data_0;
mod lemieux_offsets;
mod primitive_polynomials;
mod sobol_levitan_data_0;
mod sobol_levitan_offsets;

pub(crate) use primitive_polynomials::{
    ALT_PRIMITIVE_POLYNOMIALS, MAX_ALT_POLYNOMIALS, PPMT_MAX_DIM, PRIMITIVE_POLYNOMIALS,
};

pub(crate) static JAECKEL_OFFSETS: &[u32] = jaeckel_offsets::OFFSETS;
pub(crate) static JAECKEL_PARTS: &[&[u32]] = &[jaeckel_data_0::DATA];

pub(crate) static SOBOL_LEVITAN_OFFSETS: &[u32] = sobol_levitan_offsets::OFFSETS;
pub(crate) static SOBOL_LEVITAN_PARTS: &[&[u32]] = &[sobol_levitan_data_0::DATA];

pub(crate) static LEMIEUX_OFFSETS: &[u32] = lemieux_offsets::OFFSETS;
pub(crate) static LEMIEUX_PARTS: &[&[u32]] = &[lemieux_data_0::DATA];

pub(crate) static KUO_OFFSETS: &[u32] = kuo_offsets::OFFSETS;
pub(crate) static KUO_PARTS: &[&[u32]] = &[kuo_data_0::DATA];

pub(crate) static KUO2_OFFSETS: &[u32] = kuo2_offsets::OFFSETS;
pub(crate) static KUO2_PARTS: &[&[u32]] = &[kuo2_data_0::DATA];

pub(crate) static KUO3_OFFSETS: &[u32] = kuo3_offsets::OFFSETS;
pub(crate) static KUO3_PARTS: &[&[u32]] = &[kuo3_data_0::DATA];

pub(crate) static JOE_KUO_D5_OFFSETS: &[u32] = joe_kuo_d5_offsets::OFFSETS;
pub(crate) static JOE_KUO_D5_PARTS: &[&[u32]] = &[joe_kuo_d5_data_0::DATA];

pub(crate) static JOE_KUO_D6_OFFSETS: &[u32] = joe_kuo_d6_offsets::OFFSETS;
pub(crate) static JOE_KUO_D6_PARTS: &[&[u32]] = &[joe_kuo_d6_data_0::DATA, joe_kuo_d6_data_1::DATA];

pub(crate) static JOE_KUO_D7_OFFSETS: &[u32] = joe_kuo_d7_offsets::OFFSETS;
pub(crate) static JOE_KUO_D7_PARTS: &[&[u32]] = &[joe_kuo_d7_data_0::DATA];
