// @generated by scripts/gen_sobol_tables.py - do not edit by hand.

#[rustfmt::skip]
pub(super) static OFFSETS: &[u32] = &[
    0, 1, 3, 6, 9, 13, 17, 22, 27, 32, 37, 42, 47, 53, 59, 65,
    71, 77, 83, 90, 97, 104, 111, 118, 125, 132, 139, 146, 153, 160, 167, 174,
    181, 188, 195, 202, 209, 217, 225, 233,
];
